<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.craftingquality</groupId>
    <artifactId>selenide-junit-the-internet-project</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>selenide-junit-the-internet-project</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <java.version>22</java.version>
        <selenide.version>7.16.0</selenide.version>
        <junit.version>6.1.0-RC1</junit.version>
        <maven.surefire.version>3.5.3</maven.surefire.version>
        <rest-assured.version>6.0.0</rest-assured.version>
        <allure.version>2.35.3</allure.version>
        <maven.compiler.version>3.15.0</maven.compiler.version>
        <aspectj.version>1.9.25.1</aspectj.version>
        <env></env>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>${junit.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>${selenide.version}</version>
        </dependency>
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide-core</artifactId>
            <version>${selenide.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.javafaker</groupId>
            <artifactId>javafaker</artifactId>
            <version>1.0.2</version>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>${rest-assured.version}</version>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-jupiter</artifactId>
            <version>${allure.version}</version>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-selenide</artifactId>
            <version>${allure.version}</version>
        </dependency>
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-rest-assured</artifactId>
            <version>${allure.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Surefire for running tests -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.version}</version>
                <configuration>
                    <includes>
                        <include>**/*Tests.java</include>
                    </includes>
                    <useModulePath>false</useModulePath>
                </configuration>
            </plugin>
            <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${maven.compiler.version}</version>
        <configuration>
          <release>22</release>
          <source>22</source>
          <target>22</target>
        </configuration>
      </plugin>
      <!-- Surefire -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${maven.surefire.version}</version>
        <configuration>
          <useModulePath>false</useModulePath>
          <!-- Allure + AspectJ -->
          <argLine>
            -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
          </argLine>
          <systemPropertyVariables>
            <allure.results.directory>${project.basedir}/build/allure-results</allure.results.directory>
            <!-- URLs, browser config, etc -->
            <env>${env}</env>
            <selenide.timeout>${selenide.timeout}</selenide.timeout>
            <selenide.browser>${selenide.browser}</selenide.browser>
            <selenide.browserSize>${selenide.browserSize}</selenide.browserSize>
            <selenide.headless>${selenide.headless}</selenide.headless>
            <selenide.startMaximized>${selenide.startMaximized}</selenide.startMaximized>
          </systemPropertyVariables>
        </configuration>
        <dependencies>
          <dependency>
              <groupId>org.aspectj</groupId>
              <artifactId>aspectjweaver</artifactId>
            <version>${aspectj.version}</version>
          </dependency>
        </dependencies>
      </plugin>

      <!-- Allure Report -->
      <plugin>
        <groupId>io.qameta.allure</groupId>
        <artifactId>allure-maven</artifactId>
        <version>2.18.0</version>
        <configuration>
          <reportVersion>2.44.0</reportVersion>
          <resultsDirectory>${project.basedir}/build/allure-results</resultsDirectory>
          <reportDirectory>${project.basedir}/build/allure-report</reportDirectory>
        </configuration>
      </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>uat</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <env>uat</env>
            </properties>
        </profile>
        <profile>
            <id>production</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <properties>
                <env>production</env>
            </properties>
        </profile>
        <profile>
            <id>chrome-desktop</id>
            <properties>
                <selenide.browser>chrome</selenide.browser>
                <selenide.browserSize>1920x1080</selenide.browserSize>
                <selenide.startMaximized>true</selenide.startMaximized>
                <selenide.timeout>15000</selenide.timeout>
            </properties>
        </profile>
        <profile>
            <id>headless</id>
            <properties>
                <selenide.headless>true</selenide.headless>
            </properties>
        </profile>
    </profiles>
</project>
